version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nextjs-static-nginx
    restart: always
    ports:
      - "80:80"  # Expose port 80      
    volumes:
      - ./domain/_next:/usr/share/nginx/html/_next:ro # Map the entire _next folder
      - ./domain/404.html:/usr/share/nginx/html/404.html:ro
      - ./domain/index.html:/usr/share/nginx/html/index.html:ro
      - ./domain/logo.svg:/usr/share/nginx/html/logo.svg:ro
      - ./domain/next.svg:/usr/share/nginx/html/next.svg:ro
      - ./domain/vercel.svg:/usr/share/nginx/html/vercel.svg:ro
      - ./domain/nginx.conf:/etc/nginx/nginx.conf:ro # Map config properly
